package com.veron.enums;


public enum CashType {
    APPRO_CAISSE_EN_ENTREE,
    APPRO_CAISSE_EN_SORTIE,
    APPRO_CAISSE_VIA_LA_BANQUE,
    RETRAIT_POUR_VERSEMENT_BANQUE,
    BON_DE_COMANDE,
    DEPENSES,
    AUTRES_VERSEMENTS,
    AUTRES_RETRAITS,
    REGULARISATIONS,
    VERSEMENT_MANQUANTS,
    AVANCE_PERCUE;


}
